# .github/release.yml

changelog:
  categories:
    - title: Enhancement
      labels:
        - enhancement
    - title: Bug
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"