name: terraform workflows

on:
  push:
    branches:
      - feature/**
      - hotfix/**

  pull_request:
    branches:
      - dev
      - master
      - main

  workflow_dispatch:

jobs:
  Push:
    if: github.event_name == 'pull_request'
    uses: AutomationLibrary/actions-workflows/.github/workflows/ecr-push.yml@main
    with:
      IMAGE_NAME: "my-image"
      ## NOTE: If you are using immutable tags, SHA will always be unique.
      ## NOTE: hack to get around GitHub Action's lack of a ternary operator...
      ##         see: https://github.com/actions/runner/issues/409
      ##       in other words, this will tag the image with 'latest' on master,
      ##       and the commit SHA hash on all other branches
      IMAGE_TAG: ${{ (contains(github.base_ref, 'master') && 'latest') || github.sha }}
      ## DOCKERFILE_DIR: Defaults to the repository root. Uncomment to point to different location.
      # DOCKERFILE_DIR: "path/to/Dockerfile"
      ## DOCKER_BUILD_CONTEXT: Defaults to the repository. Uncomment to point to different location.
      # DOCKER_BUILD_CONTEXT: "path/to/context"
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_IAM_USER: ${{ secrets.AWS_IAM_USER }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  Docs:
    uses: AutomationLibrary/actions-workflows/.github/workflows/gh-pages.yml@main
    secrets:
      ACTIONS_BOT_USERNAME: ${{ secrets.ACTIONS_BOT_USERNAME }}
      ACTIONS_BOT_EMAIL: ${{ secrets.ACTIONS_BOT_EMAIL }}

