name: terraform workflows

on:
  push:
    branches:
      - feature/**
      - hotfix/**

  pull_request:
    branches:
      - dev
      - master
      - main

  workflow_dispatch:

jobs:
  Push:
    uses: chinchalinchin/github-workflows/.github/workflows/ecr-push.yml@main
    with:
      IMAGE_NAME: "my-image"
      IMAGE_TAG: $${{ github.sha }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_IAM_USER: ${{ secrets.AWS_IAM_USER }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  Update:
    uses: chinchalinchin/github-workflows/.github/workflows/lambda-update.yml@main
    with:
      FUNCTION_NAME: "my-function"
      IMAGE_NAME: "my-image"
      IMAGE_TAG: $${{ github.sha }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_IAM_USER: ${{ secrets.AWS_IAM_USER }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  Docs:
    uses: chinchalinchin/github-workflows/.github/workflows/gh-pages.yml@main

