formatter: "markdown table"

sections:
  hide:
    - providers
    - resources
    - requirements

recursive:
  enabled: true
  path: modules

output:
  file: ./docs/source/OVERVIEW.md
  mode: inject

content: |-
  {{ .Header }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}  

  ## Your Information

  Add custom information about your module here.