name: terraform workflows

on:
  push:
    branches:
      - feature/**
      - hotfix/**

  # see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:
    branches:
      - dev
      - master
      - main

  workflow_dispatch:

jobs:
  Release:
    uses: AutomationLibrary/actions-workflows/.github/workflows/release.yml@main
    # see: https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-secrets-to-nested-workflows
    secrets: inherit

  Scan:
    uses: AutomationLibrary/actions-workflows/.github/workflows/scan.yml@main
    secrets: inherit

  Lint:
    uses: AutomationLibrary/actions-workflows/.github/workflows/lint.yml@main
    secrets: inherit

  Docs:
    uses: AutomationLibrary/actions-workflows/.github/workflows/docs.yml@main
    secrets: inherit