name: terraform workflows

on:
  push:
    branches:
      - feature/**
      - hotfix/**

  pull_request:
    branches:
      - dev
      - master
      - main

  workflow_dispatch:

jobs:
  Release:
    if: ${{ github.event_name == 'pull_request' }}
    uses: chinchalinchin/github-workflows/.github/workflows/tf-release.yml@main
    with:
      MODULES: "vpc,cluster,peristence"
    secrets:
      AWS_IAM_USER: ${{ secrets.AWS_IAM_USER }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      # NOTE: Uncomment this line if your workflow requires secret Terraform variables! 
      #         See documentation /docs/source/QUICKSTART.md#TF_ENV for more info.
      # TF_ENV: ${{ secrets.TF_ENV }}

  Scan:
    if: ${{ github.event_name == 'push' }}
    uses: chinchalinchin/github-workflows/.github/workflows/tf-scan.yml@main

  Lint:
    if: ${{ github.event_name == 'push' }}
    uses: chinchalinchin/github-workflows/.github/workflows/tf-lint.yml@main

  Docs:
    if: ${{ github.event_name == 'pull_request' }}
    uses: chinchalinchin/github-workflows/.github/workflows/gh-pages.yml@main
