name: Docs

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
on: workflow_call

jobs:
  tfdocs:
    name: terraform documentation
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.ACTIONS_USERNAME }}
      EMAIL: ${{ secrets.ACTIONS_EMAIL }}
      TFDOCS_VER: 0.16.0

    steps:
      # see: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: environment
        run: echo "PATH=$(pwd)/bin:$PATH" >> $GITHUB_ENV

      - name: clone
        uses: actions/checkout@v2

      - name: cache
        id: cache_tfdocs
        uses: actions/cache@v3
        with:
          path: bin/terraform-docs
          key: ${{ github.repository }}-tfdocs

      - name: setup
        if: steps.cache_tfdocs.outputs.cache-hit != 'true'
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v${TFDOCS_VER}/terraform-docs-v${TFDOCS_VER}-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          if [ ! -d "bin" ]; then
            mkdir bin
          fi
          mv terraform-docs bin

      - name: build
        run: |
          terraform-docs markdown table --output-file README.md .
          MODS=$(ls modules/)
          pushd modules/
          for m in $MODS
          do
            pushd $m
            terraform-docs markdown table --output-file README.md .
            popd
          done
          popd

      - name: commit
        run: |
          git config user.name $USERNAME
          git config user.email $EMAIL
          git checkout -b gh-pages
          git add --all
          git add modules/
          git commit -m "$(echo $(date)) Auto-Documentation"
          git push --set-upstream origin gh-pages