name: Lint

on: workflow_call

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      # see: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: environment
        run: echo "PATH=$(pwd)/bin:$PATH" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v2

      - name: cache
        id: cache_tfdocs
        uses: actions/cache@v3
        with:
          path: bin
          key: ${{ github.repository }}-tflint

      - name: setup
        if: steps.cache_tflint.outputs.cache-hit != 'true'
        run: |
          f [ ! -d "bin" ]; then
            mkdir bin
          fi
          export TFLINT_INSTALL_PATH=$(pwd)/bin
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: lint
        run: |
          tflint --init
          tflint