name: Lint

on: workflow_call

jobs:
  tflint:
    runs-on: bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # TODO: what to cache for tflint setup?

      - name: setup
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: lint
        run: |
          tflint --init
          tflint