name: Lint

on: workflow_call

jobs:
  tflint:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3.0.2
        name: Checkout source code

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint