name: Scan

on: 
  workflow_call:

jobs:
  checkout:
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Debug
        run: |
          pwd 
          echo ${{ github.event.repository.name }}
          echo ${{ github.workspace }}
          ls -al
        
  checkov:
    name: terraform checkov scan
    runs-on: debian
    needs: checkout
    container:
      image: metzbah/automation-library:resolv
      options: --user root
      volumes:
        - ${{ github.workspace }}/${{ github.event.repository.name }}:/home/${{ github.event.repository.name }}
    steps:    
      - name: Scan with Checkov
        run: |
          pwd 
          ls -al
          cd ${{ github.event.repository.name }}
          ls -al
          checkov -d .
  
  tfsec:
    name: terraform security scan
    needs: checkout
    runs-on: debian
    steps:
      - name: Setup tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      
      - name: Run Terraform Security Scan
        run: tfsec .