name: Scan

on: 
  workflow_call:
    secrets:
      ACTIONS_USERNAME:
        required: True
      ACTIONS_EMAIL:
        required: True
      ACTIONS_PAT:
        required: True

jobs:
  # checkout:
  #   runs-on: [self-hosted]
  #   env:
  #     USERNAME: ${{ secrets.ACTIONS_USERNAME }}
  #     EMAIL: ${{ secrets.ACTIONS_EMAIL }}
  #     TOKEN: ${{ secrets.ACTIONS_PAT }}
  #   steps:
  #     - name: checkout
  #       run: |
  #         export REPO=aws-synthetics-heartbeat-canary
  #         ls -al
  #         cd ${REPO}
  #         ls -al
  #         git clone --depth 1 https://${USERNAME}:${TOKEN}@github.boozallencsn.com/AutomationLibrary/${REPO}.git
  #         cd ${REPO}

  checkov:
    # needs: checkout
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup checkov
        run: |
          apt-get -y install python3 \
            python3-pip
          pip install checkov
      
      - name: Scan with Checkov
        run: checkov -d .
  
  tfsec:
    # needs: checkout
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Setup tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      
      - name: Run Terraform Security Scan
        run: tfsec .