name: Scan

on: 
  workflow_call:
    secrets:
      ACTIONS_USERNAME:
        required: True
      ACTIONS_EMAIL:
        required: True

jobs:
  checkov:
    runs-on: [self-hosted]
    env:
      USERNAME: ${{ secrets.ACTIONS_USERNAME }}
      EMAIL: ${{ secrets.ACTIONS_EMAIL }}
    steps:
      - name:
        run: |
          git config user.name $USERNAME
          git config user.email $EMAIL
          git clone --depth 1 https://github.boozallencsn.com/AutomationLibrary/aws-synthetics-heartbeat-canary.git
          cd aws-synthetics-heartbeat-canary
      # - name: Clone repo
      #   uses: actions/checkout@v3.0.2
      
      - name: Scan with Checkov
        run: checkov -d .
  
  tfsec:
    runs-on: [self-hosted]
    env:
      USERNAME: ${{ secrets.ACTIONS_USERNAME }}
      EMAIL: ${{ secrets.ACTIONS_EMAIL }}
    steps:
      - name:
        run: |
          git config user.name $USERNAME
          git config user.email $EMAIL
          git clone --depth 1 https://github.boozallencsn.com/AutomationLibrary/aws-synthetics-heartbeat-canary.git
          cd aws-synthetics-heartbeat-canary

      # - name: Clone repo
      #   uses: actions/checkout@v3.0.2
      
      - name: Run Terraform Security Scan
        run: tfsec .