name: Scan

on: workflow_call

#jobs:
#  Checkov:
#    runs-on: [self-hosted]
#    steps:
#      - name: Clone repo
#        uses: actions/checkout@v2
#      
#      - name: Scan with Checkov
#       id: checkov
#        uses: bridgecrewiio/checkov-action@master
#        with:
#          api-key: ${{ secrets.BRIDGECREW_API_KEY }}
#          framework: terraform
#          output_format: sarif # options: cli, json, junitxml, github_failed_only, or sarif
#          # Additional paramaters can be found at: github.com/bridgecrewio/checkov-action/blob/master/action.yml
  
  tfsec:
    name: tfsec
    runs-on: [self-hosted]
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0