name: Scan

on: 
  workflow_call:
    secrets:
      ACTIONS_USERNAME:
        required: True
      ACTIONS_EMAIL:
        required: True
      ACTIONS_PAT:
        required: True

jobs:
  checkov:
    runs-on: debian
    container:
      image: metzbah/automation-library:latest
      volumes:
        - /etc/resolv.conf:/etc/resolv.conf
        - /etc/hosts:/etc/hosts
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Scan with Checkov
        run: checkov -d .
  
  tfsec:
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Setup tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      
      - name: Run Terraform Security Scan
        run: tfsec .