name: Scan

on: 
  workflow_call:
    secrets:
      ACTIONS_USERNAME:
        required: True
      ACTIONS_EMAIL:
        required: True
      PAT_TOKEN:
        required: True

jobs:
  checkout:
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        
  checkov:
    runs-on: debian
    container:
      image: metzbah/automation-library:resolv
      options: --user root
      volumes:
        - $(pwd)/${{ github.event.repository.name }}:/home/${{ github.event.repository.name }}
    steps:    
      - name: Scan with Checkov
        run: checkov -d /home/${{ github.event.repository.name }}
  
  tfsec:
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Setup tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      
      - name: Run Terraform Security Scan
        run: tfsec .