name: Scan

on: workflow_call

jobs:
  Checkov:
    runs-on: [self-hosted]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Scan with Checkov
        run: checkov -d .
  
  tfsec:
    name: tfsec
    runs-on: [self-hosted]
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      
      - name: tfsec
        run: tfsec .