name: Scan

on: 
  workflow_call:

jobs:        
  checkov:
    name: terraform checkov scan
    runs-on: debian

    steps:    
      - name: clone
        uses: actions/checkout@v2
        
      # TODO: how to cache system deps
      # --allow-unauthenticated: https://github.com/cli/cli/issues/6175
      #   i.e., only way to update repository and install dependencies until certificates are renewed.
      - name: system dependencies
        run: |
          sudo apt-get update -y --allow-unauthenticated
          sudo apt-get install -y python3-dev \
                                  python3-venv \
                                  python3-pip \
                                  build-essential

      - name: cache
        id: cache_checkov
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ github.repository }}-checkov-venv

      - name: job dependencies
        if: steps.cache_checkov.outputs.cache-hit != 'true'
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install checkov

      - name: scan
        run: |
          source .venv/bin/activate
          checkov -d .

  tfsec:
    name: terraform security scan
    runs-on: debian
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: setup
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: scan
        run: tfsec .