name: Scan

on: 
  workflow_call:

jobs:
  # checkout:
  #   runs-on: debian
  #   steps:
  #     - name: Clone repo
  #       uses: actions/checkout@v2
  #     - name: Debug
  #       run: |
  #         pwd 
  #         echo ${{ github.event.repository.name }}
  #         echo ${{ github.workspace }}
  #         ls -al
        
  checkov:
    name: terraform checkov scan
    runs-on: debian
    container:
      image: metzbah/automation-library:resolv
      volumes:
        - ${{ github.workspace }}:/home/workspace/
      options: --network=host
    steps:    
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Scan with Checkov
        run: |
          checkov -d .
    
  tfsec:
    name: terraform security scan
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Setup tfsec
        run: curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Run Terraform Security Scan
        run: tfsec .