name: Scan

on: workflow_call

jobs:
  checkov:
    runs-on: [self-hosted]
    steps:
      - name:
        run: |
          git clone --depth 1 https://github.boozallencsn.com/AutomationLibrary/aws-synthetics-heartbeat-canary.git
          cd aws-synthetics-heartbeat-canary
          
      # - name: Clone repo
      #   uses: actions/checkout@v3.0.2
      
      - name: Scan with Checkov
        run: checkov -d .
  
  tfsec:
    runs-on: [self-hosted]
    steps:
      - name:
        run: |
          git clone --depth 1 https://github.boozallencsn.com/AutomationLibrary/aws-synthetics-heartbeat-canary.git
          cd aws-synthetics-heartbeat-canary

      # - name: Clone repo
      #   uses: actions/checkout@v3.0.2
      
      - name: Run Terraform Security Scan
        run: tfsec .