name: Terraform

on: workflow_call

jobs:
  checkout:
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

  release:
    name: terraform release
    needs: checkout
    runs-on: debian
    container:
      image: metzbah/automation-library:resolv
      options: --user root
      volumes:
        - ${{ github.workspace }}/${{ github.event.repository.name }}:/home/${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Terraform Init
        run: $terraform init 

      #- name: Terraform Plan
      #  if: github.event_name == 'pull_request'
      #  run: terraform plan -no-color -input=false
      #  continue-on-error: true

      #- name: Terraform Plan Status
      #  if: steps.plan.outcome == 'failure'
      #  run: exit 1

      ## Can update conditional if default branches are different
      #- name: Terraform Apply
      #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #  run: terraform apply -auto-approve -input=false