name: Generate terraform docs

on: workflow_call

jobs:
  checkout:
    runs-on: debian
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

  tfdocs:
    name: terraform documentation
    needs: checkout
    runs-on: debian
    container:
      image: metzbah/automation-library:resolv
      options: --user root
      volumes:
        - ${{ github.workspace }}/${{ github.event.repository.name }}:/home/${{ github.event.repository.name }}
    env:
      USERNAME: ${{ secrets.ACTIONS_USERNAME }}
      EMAIL: ${{ secrets.ACTIONS_EMAIL }}
    steps:
      - name: Build TF Docs for root directory
        run: $terraform-docs markdown table --output-file README.md .

      - name: Build TF Docs for modules directory
        run: |
          MODS=$(ls modules/)
          pushd modules/
          for m in $MODS
          do
            pushd $m
            $terraform-docs markdown table --output-file README.md .
            popd
          done
          popd

#      - run: |
#          git config user.name $USERNAME
#          git config user.email $EMAIL
#          git checkout -b gh-docs
#          git status -u
#          git add --all
#          git add modules/
#          git commit -m "auto-update from terraform-docs"
#          git push --set-upstream origin gh-docs