name: Generate terraform docs

on: workflow_call

jobs:
  TF-Docs:
    runs-on: [self-hosted]
    env:
      USERNAME: ${{ secrets.ACTIONS_USERNAME }}
      EMAIL: ${{ secrets.ACTIONS_EMAIL }}
    steps:
      - uses: actions/checkout@v3

      - name: Build TF Docs for root directory
        run: terraform-docs markdown table --output-file README.md .

      - name: Build TF Docs for modules directory
        run: |
          MODS=$(ls modules/)
          pushd modules/
          for m in $MODS
          do
            pushd $m
            terraform-docs markdown table --output-file README.md .
            popd
          done
          popd

      - run: git config user.name $USERNAME
      - run: git config user.email $EMAIL
      - run: git checkout -b gh-docs
      - run: git status -u
      - run: git add --all
      - run: git add modules/
      - run: git commit -m "auto-update from terraform-docs"
      - run: git push --set-upstream origin gh-docs