name: Generate terraform docs

on: workflow_call

jobs:
  TF-Docs:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - run: MODS=$(ls modules/)

      - name: Build TF Docs in modules/ directory
        run: |
          for m in $MODS; do terraform-docs markdown table --output-file module/${m}/README.md --output-mode replace module/${m}; done

      - run: git status

      - run: git add .