name: Generate terraform docs

on: workflow_call

jobs:
  TF-Docs:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: Build TF Docs for root directory
        run: terraform-docs markdown table --output-file README.md --output-mode replace .

      - runs: pushd modules/

      - run: MODS=$(ls)

      - name: Build TF Docs in modules/ directory
        run: |
          for m in $MODS; 
          do
            echo ${m}
            pushd ${m}
            terraform-docs markdown table --output-file README.md --output-mode replace . ;
            popd
          done
          popd

      - run: git status

      - run: git add .