name: Generate terraform docs

on: workflow_call

jobs:
  TF-Docs:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: Build TF Docs for root directory
        run: terraform-docs markdown table --recursive true --output-file README.md --output-mode replace .

      - run: git status

      - run: git add .