name: Terraform Lint

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
on: workflow_call

jobs:
  tflint:
    name: terraform lint
    runs-on: ubuntu-latest

    steps:
      # see: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: environment
        run: echo "PATH=$(pwd)/bin:$PATH" >> $GITHUB_ENV

      # see: https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v2

      # see: https://github.com/actions/cache
      - name: cache
        id: cache_tflint
        uses: actions/cache@v3
        with:
          path: bin
          key: ${{ github.repository }}-tflint

      # see: https://github.com/terraform-linters/tflint/blob/b899b18a6be5e8aff7b224dad62fb772b8a5fa0f/install_linux.sh#L68
      - name: dependencies
        if: steps.cache_tflint.outputs.cache-hit != 'true'
        run: |
          if [ ! -d "bin" ]; then
            mkdir bin
          fi
          export TFLINT_INSTALL_PATH=$(pwd)/bin
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: lint
        run: |
          tflint --init
          tflint