name: Terraform Release

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
on: 
  workflow_call:
    # see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets
    secrets:
      AWS_IAM_USER:
        required: true
        description: IAM username of the AWS service account
      AWS_ACCESS_KEY_ID:
        required: true
        description: Access key ID of the AWS service account
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: Secret access key of the AWS service account
      AWS_DEFAULT_REGION:
        required: true
        description: Default region of the AWS service account
        
jobs:

  release:
    name: terraform release
    runs-on: ubuntu-latest
    env:
      # see: https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context
      AWS_IAM_USER: ${{ secrets.AWS_IAM_USER }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TERRAFORM_VERSION: 1.3.0
      TERRAFORM_STATE_KEY: ${{ github.ref ]}

    steps:
      # see: 
        # GITHUB_ENV: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        # TF_PLUGIN_CACHE_DIR: https://www.terraform.io/cli/config/config-file#provider-plugin-cache
      - name: environment
        run: |
          echo "PATH=$(pwd)/bin:$PATH" >> $GITHUB_ENV
          echo "TF_PLUGIN_CACHE_DIR=$(pwd)/plugins" >> $GITHUB_ENV

      # see: https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v2

      # see: https://github.com/actions/cache
      # NOTE: cache is keyed around `provider.tf` file. See README for more information.
      - name: terraform cache
        id: cache_terraform
        uses: actions/cache@v3
        with:
          path: bin/terraform
          key: ${{ github.repository }}-$${{ hashFiles('provider.tf')}}-tf

      - name: plugin cache
        id: cache_terraform_plugins
        uses: actions/cache@v3
        with:
          path: plugins
          key: ${{ github.repository }}-$${{ hashFiles('provider.tf')}}-tf-plugins

      # NOTE: manual install to make caching easier
      - name: dependencies
        if: steps.cache_terraform.outputs.cache-hit != 'true'
        run: |
          wget \
            -O tf.zip \
            https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip tf.zip
          if [ ! -d "bin" ]; then
            mkdir bin
          fi
          mv terraform bin/

      - name: plugins
        if: steps.cache_terraform_plugins.cache-hit != 'true'
        run: |
          if [ ! -d "plugins" ]; then
            mkdir plugins
          fi 
          terraform init \
            -input=false \
            -backend-config="key=$TERRAFORM_STATE_KEY"

      - name: plan
        run: |
          terraform plan \
            -var-file .tfvars \
            -input=false 
            
      - name: apply
        if: github.event_name == 'pull_request'
        run: |
          terraform apply \
            -var-file .tfvars \
            -input=false \
            -auto-approve 
      
      - name: destroy
        if: github.event_name == 'pull_request'
        run: |
          terraform destroy \
            -var-file .tfvars \
            -input=false \
            -auto-approve